"""
gRPC ML Serving — server side.

This is the second step in the pipeline.  It:
  1. Loads the trained model from model.pkl
  2. Implements the MLModel service defined in prediction.proto
  3. Starts a gRPC server that listens for Predict RPCs

How gRPC server calls work:
  - The client sends a PredictRequest (serialised Protobuf, binary, over HTTP/2)
  - The server deserialises it into a PredictRequest Python object
  - Our Predict() method runs the model and returns a PredictResponse
  - The response is serialised back to binary and sent over the same connection

The generated files prediction_pb2.py and prediction_pb2_grpc.py must exist
before running this script.  Generate them with:
    python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. prediction.proto

Run with:
    uv run server.py
"""

import grpc
from concurrent import futures
import numpy as np
import joblib
import prediction_pb2
import prediction_pb2_grpc


# ---------------------------------------------------------------------------
# Service implementation
#
# MLModelServicer is the base class generated by protoc from the service block
# in prediction.proto:
#
#   service MLModel {
#     rpc Predict(PredictRequest) returns (PredictResponse);
#   }
#
# Every RPC defined in the .proto file becomes an abstract method on the
# Servicer.  We override each one with our implementation logic.
# ---------------------------------------------------------------------------

class MLModelService(prediction_pb2_grpc.MLModelServicer):

    def __init__(self, model_path: str = "model.pkl"):
        # Load once at startup — not on every request.  joblib.load is not
        # thread-safe for mutable models, but sklearn predictors are read-only
        # after fitting so concurrent Predict calls are safe here.
        print(f"Loading model from {model_path}...")
        self.model   = joblib.load(model_path)
        self.version = "v1.0"
        print("Model loaded successfully")

    def Predict(self, request, context):
        """
        Handle one Predict RPC call.

        `request`  — a PredictRequest instance (deserialized from Protobuf)
                     request.features is a repeated float field, accessible
                     as a Python list.
        `context`  — gRPC ServicerContext; used to set error codes and details
                     if something goes wrong.
        """
        try:
            # request.features arrives as a repeated scalar field — convert to
            # a 2D numpy array so sklearn's predict() gets the expected shape.
            features   = np.array(request.features).reshape(1, -1)
            prediction = float(self.model.predict(features)[0])

            print(f"  request: {list(request.features)} → {prediction:.4f}")

            # Return a PredictResponse Protobuf message.  Field names match
            # exactly the names declared in prediction.proto.
            return prediction_pb2.PredictResponse(
                prediction=prediction,
                model_version=self.version,
            )

        except Exception as e:
            # Set a gRPC status code on the context so the client receives a
            # structured error (StatusCode + detail string) instead of a crash.
            # INTERNAL maps to HTTP 500 in gRPC-web and transcoding scenarios.
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(f"Prediction failed: {e}")
            return prediction_pb2.PredictResponse()


# ---------------------------------------------------------------------------
# Server setup
#
# grpc.server() returns a server backed by a thread pool.  Each incoming RPC
# call is dispatched to an available thread.  max_workers controls concurrency:
# too low → requests queue up; too high → excess threads waste memory.
# 10 is a reasonable default for a demo; production servers tune this to
# match model inference latency × expected request rate.
#
# add_insecure_port: no TLS.  For production, use add_secure_port with a
# ServerCredentials object (SSL/mTLS).  Insecure is fine for local testing.
# ---------------------------------------------------------------------------

def serve(port: int = 5000) -> None:
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))

    # Register our servicer implementation with the server
    prediction_pb2_grpc.add_MLModelServicer_to_server(MLModelService(), server)

    server.add_insecure_port(f"[::]:{port}")   # [::] binds all interfaces (IPv4 + IPv6)
    server.start()
    print(f"Server started — listening on port {port}")
    print("Press Ctrl+C to stop.\n")

    # wait_for_termination blocks the main thread until the server shuts down.
    # Without it the script would exit immediately after server.start().
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
